version: '3'
services:
  tasker:
    build: .
    container_name: tasker-api
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8001:80"
